// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Food_Details_Model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Food_Details_Model _$Food_Details_ModelFromJson(Map<String, dynamic> json) =>
    Food_Details_Model(
      json['strMeal'] as String,
      json['strInstructions'] as String,
      json['strMealThumb'] as String,
      json['strIngredient1'] as String,
      json['strIngredient2'] as String,
      json['strIngredient3'] as String,
      json['strIngredient4'] as String,
      json['strIngredient5'] as String,
      json['strIngredient6'] as String,
      json['strIngredient7'] as String,
      json['strIngredient8'] as String,
      json['strIngredient9'] as String,
      json['strIngredient10'] as String,
      json['strIngredient11'] as String,
      json['strIngredient12'] as String,
      json['strIngredient13'] as String,
      json['strIngredient14'] as String,
      json['strIngredient15'] as String,
      json['strIngredient16'] as String,
      json['strIngredient17'] as String,
      json['strIngredient18'] as String,
      json['strIngredient19'] as String,
      json['strIngredient20'] as String,
      json['strMeasure1'] as String,
      json['strMeasure2'] as String,
      json['strMeasure3'] as String,
      json['strMeasure4'] as String,
      json['strMeasure5'] as String,
      json['strMeasure6'] as String,
      json['strMeasure7'] as String,
      json['strMeasure8'] as String,
      json['strMeasure9'] as String,
      json['strMeasure10'] as String,
      json['strMeasure11'] as String,
      json['strMeasure12'] as String,
      json['strMeasure13'] as String,
      json['strMeasure14'] as String,
      json['strMeasure15'] as String,
      json['strMeasure16'] as String,
      json['strMeasure17'] as String,
      json['strMeasure18'] as String,
      json['strMeasure19'] as String,
      json['strMeasure20'] as String,
    );

Map<String, dynamic> _$Food_Details_ModelToJson(Food_Details_Model instance) =>
    <String, dynamic>{
      'strMeal': instance.strMeal,
      'strInstructions': instance.strInstructions,
      'strMealThumb': instance.strMealThumb,
      'strIngredient1': instance.strIngredient1,
      'strIngredient2': instance.strIngredient2,
      'strIngredient3': instance.strIngredient3,
      'strIngredient4': instance.strIngredient4,
      'strIngredient5': instance.strIngredient5,
      'strIngredient6': instance.strIngredient6,
      'strIngredient7': instance.strIngredient7,
      'strIngredient8': instance.strIngredient8,
      'strIngredient9': instance.strIngredient9,
      'strIngredient10': instance.strIngredient10,
      'strIngredient11': instance.strIngredient11,
      'strIngredient12': instance.strIngredient12,
      'strIngredient13': instance.strIngredient13,
      'strIngredient14': instance.strIngredient14,
      'strIngredient15': instance.strIngredient15,
      'strIngredient16': instance.strIngredient16,
      'strIngredient17': instance.strIngredient17,
      'strIngredient18': instance.strIngredient18,
      'strIngredient19': instance.strIngredient19,
      'strIngredient20': instance.strIngredient20,
      'strMeasure1': instance.strMeasure1,
      'strMeasure2': instance.strMeasure2,
      'strMeasure3': instance.strMeasure3,
      'strMeasure4': instance.strMeasure4,
      'strMeasure5': instance.strMeasure5,
      'strMeasure6': instance.strMeasure6,
      'strMeasure7': instance.strMeasure7,
      'strMeasure8': instance.strMeasure8,
      'strMeasure9': instance.strMeasure9,
      'strMeasure10': instance.strMeasure10,
      'strMeasure11': instance.strMeasure11,
      'strMeasure12': instance.strMeasure12,
      'strMeasure13': instance.strMeasure13,
      'strMeasure14': instance.strMeasure14,
      'strMeasure15': instance.strMeasure15,
      'strMeasure16': instance.strMeasure16,
      'strMeasure17': instance.strMeasure17,
      'strMeasure18': instance.strMeasure18,
      'strMeasure19': instance.strMeasure19,
      'strMeasure20': instance.strMeasure20,
    };
